### ISSUE TITLE
Weekly dev meetings for a project of this size is a terrible idea

### ISSUE THREAD

**Issue by hugbubby** [tox-user/tox-dev-meetings#20]
I'm not sure if I ever voiced this before but these meetings were a pretty bad idea from the start. A project of our size needs meetings at intervals of 2+months, not a week. Otherwise you get what happened here and people say the stuff they want to say at the first two weeks, and then the meetings become ghosttowns. We need meetings at longer intervals so people are encouraged to come every time; otherwise, what's the point?

**Comment by IngvarX** [comment]
Fixed - we don't have meetings anymore
